{% set name = "aiohttp-session" %}
{% set version = "2.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4975ad108341520a7107f5e4d482c6a9f2bbc367b9c9b08e7df524d353f5f0cb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - aiohttp >=3.0.1
    - pip
    - python >=3.5
  run:
    - aiohttp >=3.0.1
    - python >=3.5
  run_constrained:
    - aioredis >=1.0.0
    - aiomcache >=0.5.2

test:
  imports:
    - aiohttp_session

about:
  home: https://github.com/aio-libs/aiohttp-session/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: sessions for aiohttp.web
  doc_url: http://aiohttp-session.readthedocs.io/

extra:
  recipe-maintainers:
    - epruesse
